### PR TITLE
Fix Anroid 12 (SDK 31) Build error

### PR DESCRIPTION
**Pull request by MarlonJD**
Fixed error on Flutter 2.13.0.

### CODE REVIEW

**Comment by liodali** [comment]
can you provide me the error ?

**Comment by MarlonJD** [comment]
Sure

Logs:
(flutter build apk --split-per-abi -v) (only red ones)
```
[        ] e: /Users/marlonjd/flutter/flutter2/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.33.0+2/android/src/main/kotlin/hamza/dali/flutter_osm_plugin/OsmFactory.kt: (14, 1): Class 'OsmFactory'
is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
[        ] e: /Users/marlonjd/flutter/flutter2/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.33.0+2/android/src/main/kotlin/hamza/dali/flutter_osm_plugin/OsmFactory.kt: (18, 13): 'lateinit'
modifier is not allowed on properties of nullable types
[        ] e: /Users/marlonjd/flutter/flutter2/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.33.0+2/android/src/main/kotlin/hamza/dali/flutter_osm_plugin/OsmFactory.kt: (18, 13): 'lateinit'
modifier is not allowed on properties with initializer
[        ] e: /Users/marlonjd/flutter/flutter2/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.33.0+2/android/src/main/kotlin/hamza/dali/flutter_osm_plugin/OsmFactory.kt: (37, 9): Smart cast to
'FlutterOsmView' is impossible, because 'osmFlutterView' is a mutable property that could have been changed by this time
[        ] e: /Users/marlonjd/flutter/flutter2/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.33.0+2/android/src/main/kotlin/hamza/dali/flutter_osm_plugin/OsmFactory.kt: (38, 45): Smart cast to
'FlutterOsmView' is impossible, because 'osmFlutterView' is a mutable property that could have been changed by this time
[        ] e: /Users/marlonjd/flutter/flutter2/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.33.0+2/android/src/main/kotlin/hamza/dali/flutter_osm_plugin/OsmFactory.kt: (39, 16): Smart cast to
'FlutterOsmView' is impossible, because 'osmFlutterView' is a mutable property that could have been changed by this time
[   +3 ms] e: /Users/marlonjd/flutter/flutter2/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.33.0+2/android/src/main/kotlin/hamza/dali/flutter_osm_plugin/OsmFactory.kt: (42, 5): 'setActRefInView'
overrides nothing
[        ] e: /Users/marlonjd/flutter/flutter2/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.33.0+2/android/src/main/kotlin/hamza/dali/flutter_osm_plugin/OsmFactory.kt: (46, 5):
'setBindingActivity' overrides nothing
[+32800 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':flutter_osm_plugin:compileReleaseKotlin'.
[        ] > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
[        ]    > Compilation error. See log for more details
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[   +4 ms] BUİLD FAILED in 1m 14s
```

(flutter doctor -v): 
```
[✓] Flutter (Channel beta, 2.13.0-0.2.pre, on macOS 12.3.1 21E258 darwin-x64, locale tr)
    • Flutter version 2.13.0-0.2.pre at /Users/marlonjd/flutter/flutter2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8662e22bac (4 days ago), 2022-04-20 08:21:52 -0700
    • Engine revision 24a02fa5ee
    • Dart version 2.17.0 (build 2.17.0-266.5.beta)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/marlonjd/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • FF iPod touch (mobile) • be3091413ece7869d08367bf2985276a1e125390 • ios            • iOS 15.4.1 19E258
    • macOS (desktop)        • macos                                    • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by liodali** [comment]
thank you, for now i will not merge this pr sorry to say that to you 
because you're using candidate version that will affect all other devs (still not stable)
and the changes in `platformViewFactory) will break all the other plugin also
this is wrong move from flutter team
I will wait until the that version will be stable to see what we can do

**Comment by MarlonJD** [comment]
Sure thing.

**Pull request merged**
