### PR TITLE
Initializing roadWidth was commented

### PR DESCRIPTION
**Pull request by Djakh**

### CODE REVIEW

**Comment by liodali** [comment]
can you provide us why you comment the roadWidth what is you use case ?

**Comment by Djakh** [comment]
So there is a crash on ios devices due to this, the crash causes type
checking on drawMultiroad, when initializing by getting value from map data
with roadWidth it returns "5 px" means String but in the codeline it
considered as double, there fore i just commented it for now in order to
avoid crashes on ios, and also it would be great if you check case with
android, again the problem in drawMultiRoad method, if geopositions lat
long are near to each other it behaves weird

ср, 26 июн. 2024 г., 22:37 hamza mohamed ali ***@***.***>:

**Comment by liodali** [comment]
thnx for that you're right it should be changed but we can fixed in right way 
if you want i can guide to do it and then we can accept the PR
in this line 
https://github.com/liodali/osm_flutter/blob/694a71d7e94b3a9bdc4d2690ee2f156be550f51a/flutter_osm_interface/lib/src/common/utilities.dart#L177

 we just need to remove "... px" and keep `roadConf.roadOptionConfiguration?.roadWidth ?? commonRoadOption.roadWidth`
 
 do the changes i will accept it into 1.0.6 and will publish new version

**Comment by Djakh** [comment]
of course, i would be happy to work with it, it would be new experience in
native swift programming language to me, before i did not work with swift
but i can try

чт, 27 июн. 2024 г. в 00:50, hamza mohamed ali ***@***.***>:

**Comment by Djakh** [comment]
I did as you said


чт, 27 июн. 2024 г. в 14:55, Djakh ***@***.***>:

**Pull request merged**
