### PR TITLE
0.37.0

### PR DESCRIPTION
**Pull request by liodali**
* add set custom tile for osm map for now available only for android
* create LocationManager in android side
* add the support of change location marker in ios side

### CODE REVIEW

**Comment by vmwsree** [comment]
Any reason why iOS Custom tiles are not supported

**Comment by liodali** [comment]
will be supported in feature release 
also it need different implementation since we are using diff sdk for ios

**Comment by liodali** [comment]
support will added in the next version 0.38+

**Comment by liodali** [comment]
@vmwsree  check the new version `0.38.0` 
i happy to get feedback from you

**Pull request merged**
