### PR TITLE
Make compatible with flutter 2.16

### PR DESCRIPTION
**Pull request by isaacfi**
WidgetsBinding.instance in flutter 2.16.* can be null and needs a question mark '?'

### CODE REVIEW

**Comment by isaacfi** [comment]
Hi,

Can you review this push request?

BR.

**Comment by liodali** [comment]
I'm sorry to say this but this pr will not be merged you need to update your flutter version,
we don't support old version because that will mess up the current version

**Comment by isaacfi** [comment]
I tested it on 16.2 which only needs this change and won't affect flutter 3.

**Comment by liodali** [comment]
`WidgetsBinding.instance` is not nullable anymore 
if anyone put that lint as error will not build for it
bu why you don't want to upgrade your flutter version ?

**Comment by isaacfi** [comment]
I cannot upgrade because I have some plugins that have not been migrated to flutter 3, special for the dart language changes, and the builders were the most affected.

**Comment by liodali** [comment]
if you saw we already remove https://github.com/liodali/osm_flutter/commit/44f31a3e930e262da367ddb2ffbc7b5be05c3bd2
when flutter make release for 3.0
there not alternative for them 
if you want i can help you to do that?

**Comment by isaacfi** [comment]
You can help me if you give me the commit ID of the last published, so I can make a fork and add the question mark only on my repository. Because to migrate everything to Flutter 3 will be so long and I'm almost ready to publish my app to the stores

**Comment by liodali** [comment]
for now we're working on both web and 0.4X if you want you get always get update for now from the branch 0.40.0
that contain support of set custon tile on runtime on ios
we will publish new version this weekend to make this feature available for both ios and android

**Comment by isaacfi** [comment]
Sounds great @liodali 

Thanks so much by your time and support.

BR.

**Pull request closed without merging**
